[2025-07-08 18:54:34 -0300] [6705] [INFO] Starting gunicorn 21.2.0
[2025-07-08 18:54:34 -0300] [6705] [INFO] Listening at: http://127.0.0.1:8000 (6705)
[2025-07-08 18:54:34 -0300] [6705] [INFO] Using worker: sync
[2025-07-08 18:54:34 -0300] [6708] [INFO] Booting worker with pid: 6708
[2025-07-08 18:54:34 -0300] [6708] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/home/aggustin/micromamba/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'trello_clone'
[2025-07-08 18:54:34 -0300] [6708] [INFO] Worker exiting (pid: 6708)
[2025-07-08 18:54:34 -0300] [6709] [INFO] Booting worker with pid: 6709
[2025-07-08 18:54:34 -0300] [6709] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/aggustin/.vscode/venv/lib/python3.9/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/home/aggustin/micromamba/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'trello_clone'
[2025-07-08 18:54:34 -0300] [6709] [INFO] Worker exiting (pid: 6709)
[2025-07-08 18:54:34 -0300] [6705] [ERROR] Worker (pid:6708) exited with code 3
[2025-07-08 18:54:34 -0300] [6705] [ERROR] Worker (pid:6709) was sent SIGTERM!
[2025-07-08 18:54:34 -0300] [6705] [ERROR] Shutting down: Master
[2025-07-08 18:54:34 -0300] [6705] [ERROR] Reason: Worker failed to boot.
